package com.vrvsecurity.rbac.model;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Entity class representing a role in the system.
 * <p>
 * This class maps to a table in the database that holds information about roles.
 * Each role has a unique identifier and name and can be assigned to users in a role-based access control (RBAC) system.
 * </p>
 */
@Entity
@Getter
@Setter
@NoArgsConstructor
public class Role {

    /**
     * Unique identifier for the role.
     * Auto-generated by the database using an identity strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long roleId;

    /**
     * Name of the role (e.g., "ADMIN", "USER").
     * Must be unique and cannot be null.
     */
    @Column(nullable = false, unique = true)
    private String name;
}
